### ISSUE TITLE
Restructure package as described in #12

### ISSUE THREAD

**Issue by Neves-P** [rscherrer/mmmm#13]
> Still need to take the scripts out of the raphscript directory and put it in the R directory

As per @rscherrer

**Comment by Neves-P** [comment]
What is CAres and can it be removed? I'm trying to make the code pass Travis
@DeadParrot69 @rscherrer

**Comment by TimoVE9000** [comment]
Yes can be removed, it was an old model of mine that we used as an example.

**Comment by Neves-P** [comment]
@DeadParrot69, thanks, removed in `pedro`! 👍 
Will merge do delevop when Travis passes
